using Homework8._1;
Stock stock = new Stock();
Product product1 = new Product { ProductName = "Product1", StoreName = "Store1", Price = 100 };
Product product2 = new Product { ProductName = "Product2", StoreName = "Store2", Price = 200 };
Product product3 = new Product { ProductName = "Product3", StoreName = "Store3", Price = 300 };
Product product4 = new Product { ProductName = "Product4", StoreName = "Store4", Price = 400 };
Product product5 = new Product { ProductName = "Product5", StoreName = "Store5", Price = 500 };
Product product6 = new Product { ProductName = "Product6", StoreName = "Store6", Price = 600 };
stock.AddProduct(product1);
stock.AddProduct(product2);
stock.AddProduct(product3);
stock.AddProduct(product4);
stock.AddProduct(product5);
stock.AddProduct(product6);
Console.WriteLine(stock.GetProductInfoByIndex(3));
Console.WriteLine(stock.GetProductInfoByIndex(10));
Console.WriteLine(stock.GetProductInfoByName("Product7"));
Console.WriteLine(stock.GetProductInfoByName("Product2"));
Console.WriteLine($"Цена всех товаров на складе: {+stock} руб.");