using Homework8._2;
Bus bus = new Bus(65,5);
bus.BoardingPassengers("Passager1");
bus.BoardingPassengers("Passager2", "Passager3", "Passager4", "Passager5");
Console.WriteLine(bus.BoardingPassengers());
bus.PassengerDisembarkation("Passager4", "Passager3", "Passager1");
Console.WriteLine(bus.PassengerDisembarkation());
bus.BoardingPassengers("Passager6", "Passager7", "Passager8");
Console.WriteLine(bus.BoardingPassengers());
Console.WriteLine(bus.SpeedIncrease(30));
Console.WriteLine(bus.SpeedIncrease(3));
Console.WriteLine(bus.SpeedReduction(5));
Console.WriteLine(bus.SpeedReduction(100));
