using Homework8._2;
Bus bus = new Bus();
bus.BoardingPassengers("Passager1");
bus.BoardingPassengers("Passager2", "Passager3", "Passager4");
Console.WriteLine(bus.BoardingPassengers());
bus.PassengerDisembarkation("Passager2", "Passager3");
Console.WriteLine(bus.PassengerDisembarkation());
Console.WriteLine(bus.SpeedIncrease(30));
Console.WriteLine(bus.SpeedIncrease(3));
Console.WriteLine(bus.SpeedReduction(5));
Console.WriteLine(bus.SpeedReduction(100));
